### ISSUE TITLE
Removing app-profile removes routing

### ISSUE THREAD

**Issue by ToothpickFactory** [stencil-community/stencil-app-starter#51]
Took me a bit to figure out why my routing stopped working after I took out app-profile. Turns out it's because the only place stencil/router is imported is in the app-profile component. It may be better to have the example project have

```js
import '@stencil/router';
```
imported in the root aka my-app for the example project.

**Comment by david-poindexter** [comment]
It appears this issue was resolved via #57 so we'll go ahead and close this issue.  Thanks @prodrammer.
