### ISSUE TITLE
Couldn't build

### ISSUE THREAD

**Issue by wonrax** [stencil-community/stencil-app-starter#84]
I couldn't build the code. Hadn't made any change. Log:

```
$ npm run start

> stencil-getting-started@0.0.1 start
> stencil build --dev --watch --serve

[26:03.9]  @stencil/core
[26:04.3]  v2.14.0 💫
[26:10.9]  build, app, dev mode, started ...
[26:11.0]  transpile started ...
[26:18.9]  transpile finished in 7.92 s

[ ERROR ]  TypeScript: ./node_modules/@stencil/core/compiler/lib.dom.d.ts:4482:101
           Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'.Type 'HTMLElement |
           HTMLAppHomeElement | HTMLAppProfileElement | HTMLAppRootElement | HTMLAnchorElement | ... 74 more ... |
           HTMLTemplateElement' is not assignable to type 'Element'.Type 'HTMLStencilRouteLinkElement' is not
           assignable to type 'Element'.Property 'ariaLabel' is optional in type 'HTMLStencilRouteLinkElement' but
           required in type 'Element'.

   L4481:   */
   L4482:  TagName<K extends keyof HTMLElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>;
   L4483:  getElementsByTagName<K extends keyof SVGElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<SVGElementTagNameMap[K]>;

[ ERROR ]  TypeScript: ./node_modules/@stencil/core/compiler/lib.dom.d.ts:4770:101
           Type 'HTMLElementTagNameMap[K]' does not satisfy the constraint 'Element'.Type 'HTMLElement |
           HTMLAppHomeElement | HTMLAppProfileElement | HTMLAppRootElement | HTMLAnchorElement | ... 74 more ... |
           HTMLTemplateElement' is not assignable to type 'Element'.

   L4769:  getElementsByClassName(classNames: string): HTMLCollectionOf<Element>;
   L4770:  TagName<K extends keyof HTMLElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<HTMLElementTagNameMap[K]>;
   L4771:  getElementsByTagName<K extends keyof SVGElementTagNameMap>(qualifiedName: K): HTMLCollectionOf<SVGElementTagNameMap[K]>;

[ ERROR ]  TypeScript: ./node_modules/@stencil/router/dist/types/components.d.ts:105:13
           Interface 'HTMLStencilRouteLinkElement' cannot simultaneously extend types 'StencilRouteLink' and
           'HTMLStencilElement'.Named property 'ariaLabel' of types 'StencilRouteLink' and 'HTMLStencilElement' are not
           identical.

    L105:    interface HTMLStencilRouteLinkElement extends Components.StencilRouteLink, HTMLStencilElement {}
    L106:    var HTMLStencilRouteLinkElement: {

[26:18.9]  build failed, watching for changes... in 7.97 s

[26:18.9]  http://localhost:3333/
```

**Comment by MrBrunoWolff** [comment]
same here! 

Wondering if it's because of `@stencil/router:1.0.1` vs latest version(s) of `@stencil/core` ("stable" release for router is a bit old now)

Tested the default "starter app" + latest `@stencil/router` pre-release and all those errors go away... but then there's the actual "starter app" code referencing things from the older version.

**For now, the only "easy" fix is going with the classic** `skipLibCheck: false` (tsconfig.json->compilerOptions)

**Comment by wonrax** [comment]
> **For now, an "easy" fix is going with the classic** `skipLibCheck: false` (quick [reference](https://www.typescriptlang.org/tsconfig#skipLibCheck))

Thanks, I got it running finally

**Comment by rwaskiewicz** [comment]
Hey folks, sorry about that! As a temporary workaround I've pinned the Stencil version to v2.13.0 in https://github.com/ionic-team/stencil-app-starter/pull/85. I'm not going to close this issue at this time - I'm going to work to get some of our future plans for `@stencil/router` out and open, and we'll go from there. 

In the mean time, there are two workarounds for folks coming to this issue that I'd like to summarize below:

1. Setting `skipLibCheck: false` as @MrBrunoWolff suggested
2. Pinning your Stencil version to v2.13.0 for the time being

Sorry again!

**Comment by valadas** [comment]
The latest PR migrates to stencil-router-v2 which works without those bugs. I'll close this issue but feel free to comment if you guys run in to other problems or have better ideas for routing.
