### ISSUE TITLE
Add viewport-fit=cover to the meta viewport tag for stencil app projects?

### ISSUE THREAD

**Issue by Simbaclaws** [stencil-community/stencil-app-starter#88]
Dear Stencil Community,

Currently whenever I want to add for example capacitor to my stencil app to compile apps for native iOS and Android builds...
I have to add viewport-fit=cover to the viewport meta tag for each new project that I create, so that the safe area insets for both iOS and Android work.

Without it, my apps will have no safe-inset-area's, meaning content will overflow the statusbar and bottom navigator for iOS and Android.

Is there a reason why this is not added to the index.html file generated by default?

Yours truly,
Hylke

**Comment by Simbaclaws** [comment]
See:
https://developer.mozilla.org/en-US/docs/Web/CSS/env#usage

For more detail on subject matter.

**Comment by valadas** [comment]
Done in #89
