### ISSUE TITLE
An index signature parameter type must be either 'string' or 'number'.

### ISSUE THREAD

**Issue by crgardner** [stencil-community/stencil-app-starter#92]
Receiving the above error message after running npm start. Specifically, doesn't like ./node_modules/@types/babel__traverse/index.d.ts:

// this is good enough for non-visitor traverse options e.g. `noScope`
--
  | [k: `${string}\|${string}`]: VisitNode<S, Node>;
  | };

Environment

* macOs Ventura 13.6 (22G120)
* node v21.3.0
* npm 10.2.4
(tried with older versions of node and npm, too)

Reproduce
1. npm init stencil
2. Choose app [community]. Project is created.
3. Change directory to project.
4. npm install
5. npm start. Browser starts. Transpile and other activity status displayed. Then error message "An index signature parameter type must be either 'string' or 'number'" along with the babel details shown above are displayed. Alos, see the same error message in the console as well as "build failed, watching for changes"

**Comment by bitomic** [comment]
You can use [npm overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) or [yarn resolutions](https://yarnpkg.com/configuration/manifest#resolutions) to enforce an older version of `@types/babel__traverse` instead of latest.

Using yarn, you add this to your `package.json`:

```json
{
    "resolutions": {
        "@types/babel__traverse": "7.0.6"
    }
}
```

Run `yarn` to install the dependencies, and `yarn start` should work now.

**Comment by robMolloy** [comment]
Just to rewrite the previous answer more explicitly, 

You may want to add the following within package.json to give more flexibility (resolutions works with yarn, overrides works with npm, feel free to delete as it suits you)

```json
{
  "resolutions": {
    "@types/babel__traverse": "7.0.6"
  },
  "overrides": {
    "@types/babel__traverse": "7.0.6"
  }
}
```

If using yarn, run `yarn` then `yarn start`
If using npm, run `npm i` then `npm run start`

**Comment by valadas** [comment]
Many updates were done in #95 and I did not see this issue. Please give it a try and I'll reopen if this is still an issue after that.
